### ISSUE TITLE
Was working but not now

### ISSUE THREAD

**Issue by antmar904** [peterpt/eternal_scanner#12]
This is the error that I keep getting now:

**./escan: line 685: elog: command not found**

Console output:

IP/IP Range : 192.168.1.1

 User IP Input : 192.168.1.1

 Press CTRL+C (1X ONLY) to stop the scanner 

Scanner started at 14:38:44 , Please Wait
./escan: line 685: elog: command not found

Scanner stopped/finished at 14:38:44 
It was not detected in 192.168.1.1 any port 445 opened.

**Comment by peterpt** [comment]
somehow you deleted the file "elog" from this folder "/usr/local/sbin/

write this in your terminal :

wget https://raw.githubusercontent.com/peterpt/eternal_scanner/master/elog -O /usr/local/sbin/elog

and then write
chmod +x /usr/local/sbin/elog

and everything will be fine

**Comment by antmar904** [comment]
Great, that worked.  Thank you very much!
