### ISSUE TITLE
cannot scan !

### ISSUE THREAD

**Issue by belahssen** [peterpt/eternal_scanner#6]
Look Its cannot scan  : need help 👍 
 Config Port: 445 | Rate Speed: 3000 pkt/s
 User IP Input : 0.0.0.0/0
 Scanning all internet will take hours !
 Do you still want to continue ? (y/N) : y
 Press CTRL-C (1X ONLY) to stop the scanner 
Scanner started at 00:28:16 , Please Wait
^C
Scanner stopped/finished at 00:32:56 
 It was not detected in 0.0.0.0/0 any port 445 opened.
Always this => "  It was not detected in 0.0.0.0/0 any port 445 opened "<= come to me :'(

**Comment by peterpt** [comment]
make sure you have the latest masscan installed 1.0.3

**Comment by belahssen** [comment]
nothing haapend :'(

masscan 0.0.0.0/0 -p 445 --exclude 255.255.255.255

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2018-01-13 20:32:22 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 4294967295 hosts [1 port/host]
^Cwaiting several seconds to exit...                                            
saving resume file to: paused.conf

**Comment by peterpt** [comment]
leave masscan scanning with that command for 3 minutes and then abort it with CTRL+C and show me the output .

**Comment by belahssen** [comment]
nothing happend to i think i have a problem with masscan in p 445
what should i do :(

**Comment by peterpt** [comment]
let it scan for 10 minutes before you cancel the scan

**Comment by Bry-fi** [comment]
I am experiencing the same issues as well. Are you scanning from a VPS or Proxy?

**Comment by peterpt** [comment]
masscan does not scan for smb protocols , it only checks if the specific port is opened .
You both 1st should update your scripts using escan -u , and then start scanning .
The new update will reveal if any ips  where detected with port 445 opened in realtime .

Drop here your ip ranges so i can test here .

**Comment by Bry-fi** [comment]
I am going to attempt to use this tool on a server I own and see if that changes anything. I was using a local machine to see if any results would pop up.

**Comment by TrollNation** [comment]
Anyone figure out the problem to this because I cannot scan at all. I tried updating masscan and everything and no ips show up. I have no clue why it's not working for me.

**Comment by peterpt** [comment]
I have no idea what is your scenario , isp rules or whatever , but if you are running it behind a company firewall then the firewall is probably blocking your scan  .

Or you are not giving time enough for the scan to work .

**Comment by TrollNation** [comment]
I'm pretty sure 3 hours is long enough for a scan and I don't have my firewall enabled at all so not sure what the problem is
