### ISSUE TITLE
Metasploit not detected

### ISSUE THREAD

**Issue by KingDalley** [peterpt/eternal_scanner#9]
How do I fix, after I search to see if IP's are vulnerable, it says metasploit not detected ???

cat: /usr/local/share/Eternal_scanner/msflog.log: no such file or directory

**Comment by peterpt** [comment]
This is not a bug , that happens because your metasploit is not installed correctly .

from where you are running escan , write msfconsole and you will see that your metasploit is not running from that location .

**Comment by KingDalley** [comment]
how do I install metasploit correctly? Also on Parrot the scanner doesn't work either

**Comment by peterpt** [comment]
google it , this here is for bugs not for support .
